// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK8asO1Pve1OdK06inHuusnstKFPtsA38',
    appId: '1:855338763005:web:ff25b9a82cc044f129f494',
    messagingSenderId: '855338763005',
    projectId: 'the-straight-guys',
    authDomain: 'the-straight-guys.firebaseapp.com',
    storageBucket: 'the-straight-guys.firebasestorage.app',
    measurementId: 'G-QP0B9NCHT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9kNmBV5D59JE2ls9kLfielcK41x6-l18',
    appId: '1:855338763005:android:27879bb8a5585bea29f494',
    messagingSenderId: '855338763005',
    projectId: 'the-straight-guys',
    storageBucket: 'the-straight-guys.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb0VNtoq5Y5UyTld1xVQ5aalWHvbQKtAM',
    appId: '1:855338763005:ios:9e2b8901497040b229f494',
    messagingSenderId: '855338763005',
    projectId: 'the-straight-guys',
    storageBucket: 'the-straight-guys.firebasestorage.app',
    iosBundleId: 'com.example.straightGuys',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb0VNtoq5Y5UyTld1xVQ5aalWHvbQKtAM',
    appId: '1:855338763005:ios:9e2b8901497040b229f494',
    messagingSenderId: '855338763005',
    projectId: 'the-straight-guys',
    storageBucket: 'the-straight-guys.firebasestorage.app',
    iosBundleId: 'com.example.straightGuys',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK8asO1Pve1OdK06inHuusnstKFPtsA38',
    appId: '1:855338763005:web:f64a4072eeeafe3e29f494',
    messagingSenderId: '855338763005',
    projectId: 'the-straight-guys',
    authDomain: 'the-straight-guys.firebaseapp.com',
    storageBucket: 'the-straight-guys.firebasestorage.app',
    measurementId: 'G-NCGFW012J0',
  );
}
